### ISSUE TITLE
Where is Kilolib ?

### ISSUE THREAD

**Issue by mickael9** [acornejo/kilogui#1]
I see there are mentions of Kilolib in the README and it's usable on the web editor, yet I don't see it the repository. Where can one get it for offline compilation ?

**Comment by acornejo** [comment]
We had been tweaking the API before releasing it. Will post the repository URL today.

**Comment by mickael9** [comment]
Great!
I've got a few others questions if you don't mind answering them :
- What about the controller firmware and robot bootloader? Have you got
  any plans on providing the source code ?
- Can you "brick" the controller or robot ?
- What happens if your robot program has a bug that prevents communication
  with the controller ? Does the bootloader help here?
- How is this 2.0 firmware different from the K-Team's 1.0 one ?
- Can you easilly downgrade to the Kteam's 1.0 firmware ?
- Are the hex files compiled using your toolchain compatible with the ones using the K-teams's one (is the message protocol identical ?)

Thank you.

**Comment by acornejo** [comment]
Yup, no problem:

1) All will be open source, the controller firmware and the bootloader are based of kilolib, and are build targets on that repository. (i.e. if you do make on kilolib, it will produce a library file, the bootloader, and the controller).

2) Bricking the controller is easier than bricking the kilobot. (which is unfortunate since the controller is very expensive). This is part of the reason for the new firmware. In the old design, every time you upload code to the kilobots the controller is reprogrammed. In the new design, after the controller is updated, it won't be programmed again, so the risk of bricking it drops to almost zero.

3) Yes, the bootloader will help you. In fact, if you set the fuse on the processor to always jump to bootloader, then it becomes impossible to brick the kilobot once you have updated the firmware.

4) Too many differences to list all of them here. It is smaller, faster, and easier to use. Code is also generally more efficient.

5) Yes, you can easily downgrade.

6) No, it is not compatible. The message format change drastically for efficiency and robustness. The old message protocol was built using in-house techniques. The new messages use a standard CRC  check for error detection, and have a payload of 10 bytes (9 user bytes + 1 message type byte).

Feel free to ask anything else, I might put a FAQ together.

**Comment by mickael9** [comment]
Thank you for making all of this open-source, it makes life so much easier !
I'm looking forward to the Kilobot repository :)

**Comment by mickael9** [comment]
Also about the controller bricking part, are you sure it can be permanently bricked ? I thought you could always reprogram it using avrdude.

**Comment by acornejo** [comment]
Well, I guess it depends what you mean by "permanent".

If you upload the wrong hex file using avrdude, it is possible for the program running on the avr chip of the controller to create a conflict with the usb-hub chip which is also present in the controller. This effectively renders the controller unusable, since when you plug it in to the computer it will no longer be recognized as a usb host. If this happens, you cannot use avrdude to reprogram it (since avrdude requires the controller is recognized as a usb device).

We had this issue once, and we managed to fix it, but it required partially desoldering a chip, reprogramming it, and soldering it back on. I would say this definitely qualifies as "bricking" the controller, since it is always possible to fix anything if you are willing to desolder all the components.

PS: this type of problem does not occur with the kilobot, since it contains no usbhub controller, instead you can always reprogram it using avrdude through the 6 pin icsp interface. Such interface is not available in the controller.

**Comment by mickael9** [comment]
Did you use a schematic to find out all of this ?
I found a few a references to a page that described how to create your own Kilobot, but it seems to have vanished since then.

**Comment by mickael9** [comment]
Hi, are there any news about the Kilolib availability ?
I would love being able to compile offline (doesn't matter if the lib is not production-ready, that's what one would expect from a git version)

**Comment by acornejo** [comment]
Its "almost" production ready, but still need to add a few tests. The API might change slightly, but if you don't mind feel free to start using it:

https://github.com/acornejo/kilolib

All the source is there, including:
- the kilolib API (and documentation)
- the bootloader program
- the overhead controller program
- debug support.

Also, regarding your previous question about the schematic, it should be available inside a zipfile that can be downloaded from the harvard website (google kilobot ssr, and click on "how to build your own").

**Comment by mickael9** [comment]
Thanks a lot!

**Comment by mickael9** [comment]
Well, it happened, I programmed the robot bootloader in the OHC and now I'm unable to program the OHC anymore... what can I do ?

**Comment by acornejo** [comment]
First, may I ask how this happened? The reason I ask is because I would like to make this "accident" as unlikely as possible. The program-boot and program-ohc targets on the Makefile should not cause this, since the controller and the kilobot have different processors (328 vs 328p), so avrdude should refuse to program them unless forced.

I assume you have tried to run the target `make program-ohc` to try to restore your controller but it doesn't work anymore? Try it a few times, just in case the controller is not bricked. 

To unbrick it, first download the datasheet for the atmega328, and identify the diagram with the pinouts for the processor in the controller. Identify the pin that corresponds to RESET (PC6) and short it to ground using a wire.

While PC6 of the atmega328 is shorted to GND, plug in the controller to the computer. The device should no enumerate correctly. Finally, go to the kilolib folder and type `make program-ohc` but DO NOT press enter.

Now the difficult part, as soon as you remove the short from PC6 to ground, you have to hit enter in the computer. The atmega processor cannot be reprogrammed while PC6 is shorted to ground, but as soon as you let that pin go the program will start running and you have a few tenths of a second before the usbhub disconnects the controller from your computer. You need to reprogram the controller within this time.

Good luck. If that doesn't work let me know, there are other methods, but they are harder and require more components.

**Comment by mickael9** [comment]
Thanks for your reply, I will try that tomorrow.

I'm pretty sure it happened just by running `make program-boot` (I was programming a bunch of robots and had the command in my history, and then I wanted to reprogram the OHC and ran the same command after switching the jumper...). After that, there was no serial port exposed anymore (tried on Windows as well) and the RED leds on the side were lit.

**Comment by acornejo** [comment]
In that case, you're controller might not be bricked after all.

avrdude checks the signature of the processor before uploading the data, and the controller and the kilobot use different processors (328 vs 328p) which have different signatures. Therefore, `make program-boot` should not brick your controller even if the jumper is wrong, that is unless you modified the makefile so that avrdude forces programming without checking the signature.

Let me know what happens tomorrow.

**Comment by mickael9** [comment]
Well, I found an easier solution to the problem : 

```
# while true; do make program-ohc; done
```

Then plug and pray :smile: 

I tried to run make program-boot again with the OHC, and as you said, it refuses programming because of the signature mismatch. I think the explanation to this is much simpler : I had messed with kilolib and though I had reverted it, I forgot to recompile and sent a bad program to the OHC. Looking at the kernel log, I noticed that it was bootlooping (usb connect, disconnect, connect, ...) so I guess my modification was simply crashing the program which made the OHC reboot.
